# Generated by Django 4.2.5 on 2023-09-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonetwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
