# Generated by Django 4.2.5 on 2023-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0006_rename_components_choice_bonesix_component_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btwoone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=150)),
                ('no_sanction', models.CharField(max_length=100)),
                ('no_admitted', models.CharField(max_length=100)),
            ],
        ),
    ]
