# Generated by Django 4.2.5 on 2023-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0007_btwoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btwofive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('list_active_mem', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwofour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwosix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwothree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwotwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('res_sc', models.CharField(max_length=10)),
                ('res_st', models.CharField(max_length=10)),
                ('res_obc', models.CharField(max_length=10)),
                ('res_general', models.CharField(max_length=10)),
                ('res_others', models.CharField(max_length=10)),
                ('adm_sc', models.CharField(max_length=10)),
                ('adm_st', models.CharField(max_length=10)),
                ('adm_obc', models.CharField(max_length=10)),
                ('adm_general', models.CharField(max_length=10)),
                ('adm_others', models.CharField(max_length=10)),
            ],
        ),
    ]
