# Generated by Django 4.2.5 on 2023-09-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0008_btwofive_btwofour_btwosix_btwothree_btwotwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btwoeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=150)),
                ('year_join', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('year_qual', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwoeleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type_complain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwofifteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_student', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('domicile_state', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('name_program', models.CharField(max_length=100)),
                ('st_UID', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwofourteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('name_student', models.CharField(max_length=100)),
                ('cleared', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwonine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwoseven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=100)),
                ('associate_prof', models.CharField(max_length=100)),
                ('assisstant_prof', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('nature', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwoten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=500)),
                ('date_exam', models.CharField(max_length=10)),
                ('date_result', models.CharField(max_length=10)),
                ('gap', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwothirteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
                ('PO_CO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Btwotwelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
    ]
