# Generated by Django 4.2.5 on 2023-09-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0009_btwoeight_btwoeleven_btwofifteen_btwofourteen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bthreeeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('patent_number', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreeeleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=500)),
                ('name_teacher', models.CharField(max_length=500)),
                ('title_book', models.CharField(max_length=100)),
                ('title_chapter', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=100)),
                ('affiliating_inst', models.CharField(max_length=150)),
                ('name_publisher', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreefive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=500)),
                ('name_person', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('name_agency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreefour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('grant', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreefourteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('org_unit', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=100)),
                ('no_of_students', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreenine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_scholar', models.CharField(max_length=500)),
                ('name_superviser', models.CharField(max_length=500)),
                ('year_reg', models.CharField(max_length=150)),
                ('year_completed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreeone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreeseven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreesix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreeten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('name_author', models.CharField(max_length=500)),
                ('teacher_dept', models.CharField(max_length=150)),
                ('name_journal', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=500)),
                ('issn', models.CharField(max_length=500)),
                ('link_website', models.CharField(max_length=150)),
                ('link_article', models.CharField(max_length=100)),
                ('listed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreethirteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=500)),
                ('purpose', models.CharField(max_length=150)),
                ('list_activities', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreethree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=500)),
                ('fellowship_name', models.CharField(max_length=100)),
                ('financial_support', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('agency', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreetwelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bthreetwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
    ]
