# Generated by Django 4.2.5 on 2023-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0010_bthreeeight_bthreeeleven_bthreefive_bthreefour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bthreefifteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=500)),
                ('purpose', models.CharField(max_length=150)),
                ('list_activities', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='bthreethirteen',
            old_name='date',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bthreethirteen',
            old_name='purpose',
            new_name='org',
        ),
        migrations.RemoveField(
            model_name='bthreethirteen',
            name='list_activities',
        ),
        migrations.RemoveField(
            model_name='bthreethirteen',
            name='year',
        ),
        migrations.AlterField(
            model_name='bthreethirteen',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
