# Generated by Django 4.2.5 on 2023-09-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0011_bthreefifteen_rename_date_bthreethirteen_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bfourfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfourfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfourone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfourseven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfoursix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_mix_edit', models.CharField(max_length=500)),
                ('lcs', models.CharField(max_length=150)),
                ('central_inst', models.CharField(max_length=500)),
                ('animal_house', models.CharField(max_length=500)),
                ('museum', models.CharField(max_length=500)),
                ('business_lab', models.CharField(max_length=500)),
                ('reasearch', models.CharField(max_length=500)),
                ('mootcourt', models.CharField(max_length=500)),
                ('theatre', models.CharField(max_length=500)),
                ('art', models.CharField(max_length=500)),
                ('others', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bfourthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfourtwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_expenditure', models.CharField(max_length=500)),
                ('item', models.CharField(max_length=150)),
                ('infra_expenditure', models.CharField(max_length=500)),
                ('book_expenditure', models.CharField(max_length=500)),
                ('physical_expenditure', models.CharField(max_length=500)),
                ('salary_expenditure', models.CharField(max_length=500)),
                ('other_expenditure', models.CharField(max_length=500)),
            ],
        ),
    ]
