# Generated by Django 4.2.5 on 2023-09-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0012_bfourfive_bfourfour_bfourone_bfourseven_bfoursix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bfiveeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_st', models.CharField(max_length=150)),
                ('name_event', models.CharField(max_length=150)),
                ('date_event', models.CharField(max_length=150)),
                ('team_individual', models.CharField(max_length=150)),
                ('type_int', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('name_org', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfiveeleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfivefive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=500)),
                ('student_placed', models.CharField(max_length=150)),
                ('org_placed', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfivefour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bfivenine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfiveone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('no_of_students', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=150)),
                ('agency', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfiveseven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=500)),
                ('name_st', models.CharField(max_length=150)),
                ('year_qual', models.CharField(max_length=100)),
                ('name_exam', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfivesix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=500)),
                ('higher_ed', models.CharField(max_length=150)),
                ('org', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfiveten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=500)),
                ('date_event', models.CharField(max_length=150)),
                ('type_event', models.CharField(max_length=100)),
                ('name_event', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bfivethree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bfivetwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('add_info', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
