# Generated by Django 4.2.5 on 2023-09-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0015_aonefive_aonefour_aoneone_aonethree_aonetwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boneseven',
            name='year',
            field=models.IntegerField(default=9999),
        ),
    ]
