# Generated by Django 4.2.5 on 2023-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0016_boneseven_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boneseven',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
