# Generated by Django 4.2.5 on 2023-10-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0019_btwoone_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='btwoseven',
            name='year_app',
            field=models.CharField(default=2012, max_length=100),
            preserve_default=False,
        ),
    ]
