# Generated by Django 4.2.5 on 2023-10-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonethree', '0020_btwoseven_year_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='btwofifteen',
            name='year_join',
            field=models.CharField(default=2012, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btwofourteen',
            name='year',
            field=models.CharField(default=2012, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btwoten',
            name='year',
            field=models.CharField(default=2012, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='btwofifteen',
            name='year',
            field=models.CharField(max_length=5),
        ),
    ]
